services:
  configSrv:
    image: mongo:latest
    container_name: configSrv 
    restart: always
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.31
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "configSrv",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1_1:
    image: mongo:latest
    container_name: shard1_1
    restart: always
    ports:
      - "27017:27018"
    networks:
      app-network:
        ipv4_address: 173.17.0.11
    volumes:
      - shard1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s


  shard2_1:
    image: mongo:latest
    container_name: shard1_1
    restart: always
    ports:
      - "27017:27018"
    networks:
      app-network:
        ipv4_address: 173.17.0.21
    volumes:
      - shard1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s


  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - configSrv
      - mongos_router1
      - mongos_router2
      - shard1-1
      - shard2-1
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router1"
      MONGODB_DATABASE_NAME: "somedb"


volumes:
  mongodb1_data_container: